// Launch Action
export const LAUNCH_REQUEST = "LAUNCH_REQUEST"
export const LAUNCH_RESPONSE = "LAUNCH_RESPONSE"
export const SET_LAUNCH_DATA = "SET_LAUNCH_DATA"
export const CLEAR_LAUNCH_DATA = "CLEAR_LAUNCH_DATA"
export const UPDATE_PAGINATION_INDEX = "UPDATE_PAGINATION_INDEX" 

// Rocket Action
export const SET_ROCKET_DATA = "SET_ROCKET_DATA"
export const ROCKET_REQUEST = "ROCKET_REQUEST"
export const ROCKET_RESPONSE = "ROCKET_RESPONSE"
export const CLEAR_ROCKET_DATA = "CLEAR_ROCKET_DATA"